FROM lendableuk/php-fpm-alpine:7.4.9-alpine3.11

COPY --from=composer:2.0.13 /usr/bin/composer /usr/bin/composer

COPY . /app
WORKDIR /app

RUN chown -R 'app:app' /app && \
    su app -c "composer install --prefer-dist --no-progress -n --ansi" && \
    su app -c "composer clear-cache --ansi -n"

