FROM lendableuk/php-fpm-alpine:8.1.11-alpine3.15

COPY --from=composer:2.6.5 /usr/bin/composer /usr/bin/composer

COPY . /app
WORKDIR /app

RUN chown -R 'app:app' /app && \
    su app -c "composer install --prefer-dist --no-progress -n --ansi" && \
    su app -c "composer clear-cache --ansi -n"
