name: "CI"

concurrency:
  group: "ci-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

on:
  merge_group:
  pull_request:
  push:
    branches:
      - "master"

permissions:
  contents: read

jobs:
  static-analysis:
    name: "Static analysis"
    runs-on: ubuntu-24.04
    container:
      image: public.ecr.aws/docker/library/php:8.3-cli-alpine
      env:
        COMPOSER_ALLOW_SUPERUSER: true
        COMPOSER_ROOT_VERSION: dev-master

    steps:
      - name: "Install bash, git"
        run: apk add --no-cache bash git

      - name: "Install Composer"
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer --version=2.9.8

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: "Install dependencies"
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: "Validate Composer dependencies"
        run: composer validate

      - name: "Check Composer dependency licenses"
        run: composer licenses:check

      - name: "Run linting"
        run: composer lint

      - name: "Run coding style"
        run: composer code-style:check

      - name: "Run PHPStan"
        run: composer phpstan

      - name: "Run Rector"
        run: composer rector:check

  tests:
    name: "Tests (PHP ${{ matrix.php-version }}, ${{ matrix.dependencies }} deps)"
    runs-on: ubuntu-24.04
    container:
      image: public.ecr.aws/docker/library/php:${{ matrix.php-version }}-cli-alpine
      env:
        COMPOSER_ALLOW_SUPERUSER: true
        COMPOSER_ROOT_VERSION: dev-master

    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "lowest"
          - "highest"
          - "locked"
        php-version:
          - "8.3"
          - "8.4"
          - "8.5"

    steps:
      - name: "Install bash, git, and pcov"
        run: |
          apk add --no-cache bash git $PHPIZE_DEPS
          pecl install pcov
          docker-php-ext-enable pcov

      - name: "Install Composer"
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer --version=2.9.8

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: "Update Composer platform version"
        if: ${{ matrix.dependencies != 'locked' && matrix.php-version != '8.3' }}
        run: composer config platform.php ${{ matrix.php-version }}

      - name: "Install dependencies"
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "Run tests"
        run: composer tests
